export const nigeriaStates = [
  "Search complains by state",
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
  "FCT Abuja",
];

export const nigeriaLGAs = [
  "Aba North",
  "Aba South",
  "Arochukwu",
  "Bende",
  "Ikwuano",
  "Isiala Ngwa North",
  "Isiala Ngwa South",
  "Isuikwuato",
  "Obi Ngwa",
  "Ohafia",
  "Osisioma",
  "Ugwunagbo",
  "Ukwa East",
  "Ukwa West",
  "Umuahia North",
  "Umuahia South",
  "Umu Nneochi",
  "Demsa",
  "Fufure",
  "Ganye",
  "Gayuk",
  "Gombi",
  "Grie",
  "Hong",
  "Jada",
  "Lamurde",
  "Madagali",
  "Maiha",
  "Mayo Belwa",
  "Michika",
  "Mubi North",
  "Mubi South",
  "Numan",
  "Shelleng",
  "Song",
  "Toungo",
  "Yola North",
  "Yola South",
  "Abak",
  "Eastern Obolo",
  "Eket",
  "Esit Eket",
  "Essien Udim",
  "Etim Ekpo",
  "Etinan",
  "Ibeno",
  "Ibesikpo Asutan",
  "Ibiono-Ibom",
  "Ika",
  "Ikono",
  "Ikot Abasi",
  "Ikot Ekpene",
  "Ini",
  "Itu",
  "Mbo",
  "Mkpat-Enin",
  "Nsit-Atai",
  "Nsit-Ibom",
  "Nsit-Ubium",
  "Obot Akara",
  "Okobo",
  "Onna",
  "Oron",
  "Oruk Anam",
  "Udung-Uko",
  "Ukanafun",
  "Uruan",
  "Urue-Offong/Oruko",
  "Uyo",
  "Aguata",
  "Anambra East",
  "Anambra West",
  "Anaocha",
  "Awka North",
  "Awka South",
  "Ayamelum",
  "Dunukofia",
  "Ekwusigo",
  "Idemili North",
  "Idemili South",
  "Ihiala",
  "Njikoka",
  "Nnewi North",
  "Nnewi South",
  "Ogbaru",
  "Onitsha North",
  "Onitsha South",
  "Orumba North",
  "Orumba South",
  "Oyi",
  "Alkaleri",
  "Bauchi",
  "Bogoro",
  "Damban",
  "Darazo",
  "Dass",
  "Gamawa",
  "Ganjuwa",
  "Giade",
  "Itas/Gadau",
  "Jama'are",
  "Katagum",
  "Kirfi",
  "Misau",
  "Ningi",
  "Shira",
  "Tafawa Balewa",
  "Toro",
  "Warji",
  "Zaki",
  "Brass",
  "Ekeremor",
  "Kolokuma/Opokuma",
  "Nembe",
  "Ogbia",
  "Sagbama",
  "Southern Ijaw",
  "Yenagoa",
  "Agatu",
  "Apa",
  "Ado",
  "Buruku",
  "Gboko",
  "Guma",
  "Gwer East",
  "Gwer West",
  "Katsina-Ala",
  "Konshisha",
  "Kwande",
  "Logo",
  "Makurdi",
  "Obi",
  "Ogbadibo",
  "Ohimini",
  "Oju",
  "Okpokwu",
  "Oturkpo",
  "Tarka",
  "Ukum",
  "Ushongo",
  "Vandeikya",
  "Abadam",
  "Askira/Uba",
  "Bama",
  "Bayo",
  "Biu",
  "Chibok",
  "Damboa",
  "Dikwa",
  "Gubio",
  "Guzamala",
  "Gwoza",
  "Hawul",
  "Jere",
  "Kaga",
  "Kala/Balge",
  "Konduga",
  "Kukawa",
  "Kwaya Kusar",
  "Mafa",
  "Magumeri",
  "Maiduguri",
  "Marte",
  "Mobbar",
  "Monguno",
  "Ngala",
  "Nganzai",
  "Shani",
  "Abi",
  "Akamkpa",
  "Akpabuyo",
  "Bakassi",
  "Bekwarra",
  "Biase",
  "Boki",
  "Calabar Municipal",
  "Calabar South",
  "Etung",
  "Ikom",
  "Obanliku",
  "Obubra",
  "Obudu",
  "Odukpani",
  "Ogoja",
  "Yakuur",
  "Yala",
  "Aniocha North",
  "Aniocha South",
  "Bomadi",
  "Burutu",
  "Ethiope East",
  "Ethiope West",
  "Ika North East",
  "Ika South",
  "Isoko North",
  "Isoko South",
  "Ndokwa East",
  "Ndokwa West",
  "Okpe",
  "Oshimili North",
  "Oshimili South",
  "Patani",
  "Sapele",
  "Udu",
  "Ughelli North",
  "Ughelli South",
  "Ukwuani",
  "Uvwie",
  "Warri North",
  "Warri South",
  "Warri South West",
  "Afikpo North",
  "Afikpo South",
  "Ebonyi",
  "Ezza North",
  "Ezza South",
  "Ikwo",
  "Ishielu",
  "Ivo",
  "Izzi",
  "Ohaozara",
  "Ohaukwu",
  "Onicha",
  "Akoko-Edo",
  "Egor",
  "Esan Central",
  "Esan North-East",
  "Esan South-East",
  "Esan West",
  "Etsako Central",
  "Etsako East",
  "Etsako West",
  "Igueben",
  "Ikpoba-Okha",
  "Oredo",
  "Orhionmwon",
  "Ovia North-East",
  "Ovia South-West",
  "Owan East",
  "Owan West",
  "Uhunmwonde",
  "Ado Ekiti",
  "Efon",
  "Ekiti East",
  "Ekiti South-West",
  "Ekiti West",
  "Emure",
  "Gbonyin",
  "Ido Osi",
  "Ijero",
  "Ikere",
  "Ikole",
  "Ilejemeje",
  "Irepodun/Ifelodun",
  "Ise/Orun",
  "Moba",
  "Oye",
  "Aninri",
  "Awgu",
  "Enugu East",
  "Enugu North",
  "Enugu South",
  "Ezeagu",
  "Igbo Etiti",
  "Igbo Eze North",
  "Igbo Eze South",
  "Isi Uzo",
  "Nkanu East",
  "Nkanu West",
  "Nsukka",
  "Oji River",
  "Udenu",
  "Udi",
  "Uzo-Uwani",
  "Akko",
  "Balanga",
  "Billiri",
  "Dukku",
  "Funakaye",
  "Gombe",
  "Kaltungo",
  "Kwami",
  "Nafada",
  "Shongom",
  "Yamaltu/Deba",
  "Aboh Mbaise",
  "Ahiazu Mbaise",
  "Ehime Mbano",
  "Ezinihitte",
  "Ideato North",
  "Ideato South",
  "Ihitte/Uboma",
  "Ikeduru",
  "Isiala Mbano",
  "Isu",
  "Mbaitoli",
  "Ngor Okpala",
  "Njaba",
  "Nkwerre",
  "Nwangele",
  "Obowo",
  "Oguta",
  "Ohaji/Egbema",
  "Okigwe",
  "Orlu",
  "Orsu",
  "Oru East",
  "Oru West",
  "Owerri Municipal",
  "Owerri North",
  "Owerri West",
  "Abi",
  "Yala",
  "Boki",
  "Obudu",
  "Obanliku",
  "Calabar Municipal",
  "Calabar South",
  "Akpabuyo",
  "Bakassi",
  "Biase",
  "Yakurr",
  "Obubra",
  "Etung",
  "Ikom",
  "Ogoja",
  "Bekwara",
  "Obubra",
  "Yakuur",
  "Akwanga",
  "Awe",
  "Doma",
  "Karu",
  "Keana",
  "Keffi",
  "Kokona",
  "Lafia",
  "Nasarawa",
  "Nasarawa Eggon",
  "Obi",
  "Wamba",
  "Abaji",
  "Bwari",
  "Gwagwalada",
  "Kuje",
  "Kwali",
  "Municipal Area Council",
  "Abeokuta North",
  "Abeokuta South",
  "Ado-Odo/Ota",
  "Egbado North",
  "Egbado South",
  "Ewekoro",
  "Ifo",
  "Ijebu East",
  "Ijebu North",
  "Ijebu North East",
  "Ijebu Ode",
  "Ikenne",
  "Imeko Afon",
  "Ipokia",
  "Obafemi Owode",
  "Odeda",
  "Odogbolu",
  "Ogun Waterside",
  "Remo North",
  "Sagamu",
  "Akure North",
  "Akure South",
  "Ese Odo",
  "Idanre",
  "Ifedore",
  "Ilaje",
  "Ile Oluji/Okeigbo",
  "Irele",
  "Odigbo",
  "Okitipupa",
  "Ondo East",
  "Ondo West",
];

export const navigationLinks = [
  {
    label: "Home",
    href: "/",
  },

  {
    label: "Complains",
    href: "/complains",
  },
  {
    label: "Report Issue",
    href: "/report-issues",
  },
  {
    label: "Dashboard",
    href: "/dashboard",
  },
];

export const footerLinks = [
  {
    label: "FAQs",
    href: "/#faq",
  },


  {
    label: "Privacy Policy",
    href: "/privacy-policy",
  },
  {
    label: "Terms of Service",
    href: "/terms-of-service",
  },
];

export const missions = [
  "Empower citizens to report community issues effectively.",
  "Enhance accountability and transparency in governance.",
  "Reduce response time to citizen-reported issues.",
  "Strengthen community bonds and solidarity.",
  "Build trust between citizens and government agencies.",
];
export const howItWorks = [
  {
    step: "Step 1",
    text: "Submit your report with details and photos",
    picture: "/create-account.png",
  },
  {
    step: "Step 2",
    text: "Authorities track, review and respond to your report.",
    picture: "/authorities-track-report.png",
  },
  {
    step: "Step 3",
    text: "Track the progress and resolution of your reported issue",
    picture: "/track-change-in-report.png",
  },
];

export const reportIssuesOn = [
  {
    title: "Infrastructure",
    href: "/report-issues/infrastructure",
    picture: "/infrastructure-bridge.jpg",
    text: "Report issues related to public infrastructure such as roads, bridges, water supply, electricity, and public transportation.",
  },
  {
    title: "Education",
    href: "/report-issues/education",
    picture: "/education-books.jpg",
    text: "Notify about concerns regarding school facilities, teaching materials, teacher shortages, and access to education",
  },
  {
    title: "Unemployment",
    href: "/report-issues/unemployment",
    picture: "/employment.jpg",
    text: "Highlight challenges such as job shortages, inequitable hiring practices, and barriers to entrepreneurship.",
  },
  {
    title: "Security",
    href: "/report-issues/security",
    picture: "/security-camera.jpg",
    text: "Raise awareness on matters like crime rates, vandalism, public safety risks, and law enforcement issues",
  },
  {
    title: "Governance",
    href: "/report-issues/governance",
    picture: "/governance-rule-of-law.jpg",
    text: "Report problems including corruption, transparency deficits, bureaucratic inefficiencies, and local governance shortcomings",
  },
  {
    title: "Transportation",
    href: "/report-issues/transportation",
    picture: "/transportation-cars.jpg",
    text: "Identify problems such as traffic congestion, delays in public transit, pedestrian safety hazards, and accessibility issues in transport.",
  },
  {
    title: "Social Issues",
    href: "/report-issues/social-issues",
    picture: "/social-issues-inequalities.jpg",
    text: "Bring attention to issues such as homelessness, substance abuse, domestic violence, discrimination, and access to social services",
  },
  {
    title: "Economic Issues",
    href: "/report-issues/economic-issues",
    picture: "/people-holding-banner-seeking-support.jpg",
    text: "Flag concerns such as poverty levels, economic disparities, job availability, cost of living challenges, and financial access issues",
  },
];

export const FAQs = [
  {
    question: "What types of issues can I report on this platform?",
    answer:
      "You can report a wide range of issues, including infrastructure problems, educational concerns, unemployment challenges, security issues, governance matters, transportation problems, social issues, and economic concerns.",
    item: "item-1",
  },
  {
    question: "How do I submit a report?",
    answer:
      "To submit a report, simply click on the 'Submit Report' button, fill in the required details, choose the relevant category, and provide any supporting documents or photos. Then, click 'Submit' to send your report.",
    item: "item-2",
  },
  {
    question: "Will my report remain anonymous?",
    answer:
      "Yes, you can choose to submit your report anonymously. However, providing your contact information may help authorities follow up with you for additional details if needed.",
    item: "item-3",
  },
  {
    question: "How can I track the status of my report?",
    answer:
      "After submitting a report, you can track its status by logging into your account and checking the 'My Reports' section. You will receive updates on any progress or actions taken.",
    item: "item-4",
  },
  {
    question: "What happens after I submit a report?",
    answer:
      "Once you submit a report, it is routed to the appropriate government department or authority. They will review the issue, take necessary action, and update the status of the report on the platform.",
    item: "item-5",
  },
  {
    question: "Can I report multiple issues?",
    answer:
      "Yes, you can report multiple issues. For each issue, you will need to submit a separate report to ensure it is directed to the relevant department for resolution.",
    item: "item-6",
  },
  {
    question: "How long does it take for a report to be addressed?",
    answer:
      "The time it takes to address a report can vary depending on the nature of the issue and the responsible department. You can track the progress through the platform and receive updates.",
    item: "item-7",
  },
  {
    question: "Who can see my report?",
    answer:
      "Your report will be visible to the relevant authorities and, depending on your privacy settings, other users on the platform. You can choose to make your report public or keep it private.",
    item: "item-8",
  },
  {
    question: "How do I provide feedback about the platform?",
    answer:
      "We welcome your feedback! You can provide feedback by clicking on the 'Feedback' link at the bottom of the page and filling out the feedback form. Your input helps us improve the platform.",
    item: "item-9",
  },
  {
    question: "Is there a mobile app for this platform?",
    answer:
      "No, we  don't have a mobile app available now for both Android and iOS devices.",
    item: "item-10",
  },
];

export const createUser = [
  {
    label: "Sign in",
    href: "/sign-in",
  },
  {
    label: "Create account",
    href: "/sign-up",
  },
];

export const complainSidebar = [
  {
    label: "Infrastructure",
    picture: "/bridge.png",
    href: "/report-issues/infrastructure",
  },
  {
    label: "Economic Issues",
    picture: "/job-loss.png",
    href: "/report-issues/economic-issues",
  },
  {
    label: "Transportation",
    picture: "/car-accident.png",
    href: "/report-issues/transportation",
  },
  {
    label: "Governance",
    picture: "/court.png",
    href: "/report-issues/governance",
  },
  {
    label: "Security",
    picture: "/gun.png",
    href: "/report-issues/security",
  },
  {
    label: "Employment",
    picture: "/poverty.png",
    href: "/report-issues/employment",
  },
  {
    label: "Social Issues",
    picture: "/inequality.png",
    href: "/report-issues/social-issues",
  },
  {
    label: "Education",
    picture: "/graduate.png",
    href: "/report-issues/education",
  },
];

export const dummyData = [
  {
    profileImage: "https://avatar.iran.liara.run/public/boy?username=kinglsey",
    fullName: "Chukwu sabastine",
    dateOfPosting: "02/04/2024",
    issue: "Employment",
    state: "Enugu",
    reportImage: "/people-holding-banner-seeking-support.jpg",
    reportDesc:
      "A user dashboard should provide a comprehensive and user-friendly interface that allows users to manage their reports, track the status of their issues, receive notifications, and interact with the platform. Here's a conceptual layout and key components for the dashboard:",
    reportNumberOfComment: 6,
    reportUpvote: 4,
  },
  {
    profileImage: "https://avatar.iran.liara.run/public/boy?username=kinglsey",
    fullName: "Chukwu sabastine",
    dateOfPosting: "02/04/202",
    issue: "Employment",
    state: "Enugu",

    reportImage: "/people-holding-banner-seeking-support.jpg",
    reportDesc:
      "A user dashboard should provide a comprehensive and user-friendly interface that allows users to manage their reports, track the status of their issues, receive notifications, and interact with the platform. Here's a conceptual layout and key components for the dashboard:",
    reportNumberOfComment: 6,
    reportUpvote: 4,
  },
  {
    profileImage: "https://avatar.iran.liara.run/public/boy?username=kinglsey",
    fullName: "Chukwu sabastine",
    dateOfPosting: "02/04/2024",
    issue: "Employment",
    state: "Enugu",

    reportImage: "/people-holding-banner-seeking-support.jpg",
    reportDesc:
      "A user dashboard should provide a comprehensive and user-friendly interface that allows users to manage their reports, track the status of their issues, receive notifications, and interact with the platform. Here's a conceptual layout and key components for the dashboard:",
    reportNumberOfComment: 6,
    reportUpvote: 4,
  },
  {
    profileImage: "https://avatar.iran.liara.run/public/boy?username=kinglsey",
    fullName: "Chukwu sabastine",
    dateOfPosting: "02/04/2024",
    issue: "Employment",
    state: "Enugu",

    reportImage: "/people-holding-banner-seeking-support.jpg",
    reportDesc:
      "A user dashboard should provide a comprehensive and user-friendly interface that allows users to manage their reports, track the status of their issues, receive notifications, and interact with the platform. Here's a conceptual layout and key components for the dashboard:",
    reportNumberOfComment: 6,
    reportUpvote: 4,
  },
  {
    profileImage: "https://avatar.iran.liara.run/public/boy?username=kinglsey",
    fullName: "Chukwu sabastine",
    dateOfPosting: "02/04/2024",
    issue: "Employment",
    state: "Enugu",

    reportImage: "/people-holding-banner-seeking-support.jpg",
    reportDesc:
      "A user dashboard should provide a comprehensive and user-friendly interface that allows users to manage their reports, track the status of their issues, receive notifications, and interact with the platform. Here's a conceptual layout and key components for the dashboard:",
    reportNumberOfComment: 6,
    reportUpvote: 4,
  },
  {
    profileImage: "https://avatar.iran.liara.run/public/boy?username=kinglsey",
    fullName: "Chukwu sabastine",
    dateOfPosting: "02/04/2024",
    issue: "Employment",
    state: "Enugu",

    reportImage: "/people-holding-banner-seeking-support.jpg",
    reportDesc:
      "A user dashboard should provide a comprehensive and user-friendly interface that allows users to manage their reports, track the status of their issues, receive notifications, and interact with the platform. Here's a conceptual layout and key components for the dashboard:",
    reportNumberOfComment: 6,
    reportUpvote: 4,
  },
];

export const dummyComment = [
  {
    userPicture: "https://avatar.iran.liara.run/public/boy?username=kinglsey",
    fullName: "casmanny",
    comment:
      "This problem is really ravaging our community, we seriously needs the government intervention.",
  },
  {
    userPicture: "https://avatar.iran.liara.run/public/boy?username=kinglsey",
    fullName: "casmanny",
    comment:
      "This problem is really ravaging our community, we seriously needs the government intervention.",
  },
  {
    userPicture: "https://avatar.iran.liara.run/public/boy?username=kinglsey",
    fullName: "casmanny",
    comment:
      "This problem is really ravaging our community, we seriously needs the government intervention.",
  },
];

export const dummyDashboardData = [
  {
    report:
      "I am reporting an issue of unfair dismissal and lack of benefits at XYZ Manufacturing Company, located in the Ikeja Industrial Area of Lagos. Several employees, including myself, have been dismissed without proper notice or severance pay, which is against the labor laws in Nigeria.",
    reportStatus: "submited",
    dateReportWasMade: "2/07/2024",
  },
  {
    report:
      "I am reporting an issue of unfair dismissal and lack of benefits at XYZ Manufacturing Company, located in the Ikeja Industrial Area of Lagos. Several employees, including myself, have been dismissed without proper notice or severance pay, which is against the labor laws in Nigeria.",
    reportStatus: "submited",
    dateReportWasMade: "2/07/2024",
  },
  {
    report:
      "I am reporting an issue of unfair dismissal and lack of benefits at XYZ Manufacturing Company, located in the Ikeja Industrial Area of Lagos. Several employees, including myself, have been dismissed without proper notice or severance pay, which is against the labor laws in Nigeria.",
    reportStatus: "submited",
    dateReportWasMade: "2/07/2024",
  },
  {
    report:
      "I am reporting an issue of unfair dismissal and lack of benefits at XYZ Manufacturing Company, located in the Ikeja Industrial Area of Lagos. Several employees, including myself, have been dismissed without proper notice or severance pay, which is against the labor laws in Nigeria.",
    reportStatus: "submited",
    dateReportWasMade: "2/07/2024",
  },
  {
    report:
      "I am reporting an issue of unfair dismissal and lack of benefits at XYZ Manufacturing Company, located in the Ikeja Industrial Area of Lagos. Several employees, including myself, have been dismissed without proper notice or severance pay, which is against the labor laws in Nigeria.",
    reportStatus: "submited",
    dateReportWasMade: "2/07/2024",
  },
  {
    report:
      "I am reporting an issue of unfair dismissal and lack of benefits at XYZ Manufacturing Company, located in the Ikeja Industrial Area of Lagos. Several employees, including myself, have been dismissed without proper notice or severance pay, which is against the labor laws in Nigeria.",
    reportStatus: "submited",
    dateReportWasMade: "2/07/2024",
  },
  {
    report:
      "I am reporting an issue of unfair dismissal and lack of benefits at XYZ Manufacturing Company, located in the Ikeja Industrial Area of Lagos. Several employees, including myself, have been dismissed without proper notice or severance pay, which is against the labor laws in Nigeria.",
    reportStatus: "submited",
    dateReportWasMade: "2/07/2024",
  },
  {
    report:
      "I am reporting an issue of unfair dismissal and lack of benefits at XYZ Manufacturing Company, located in the Ikeja Industrial Area of Lagos. Several employees, including myself, have been dismissed without proper notice or severance pay, which is against the labor laws in Nigeria.",
    reportStatus: "submited",
    dateReportWasMade: "2/07/2024",
  },
  {
    report:
      "I am reporting an issue of unfair dismissal and lack of benefits at XYZ Manufacturing Company, located in the Ikeja Industrial Area of Lagos. Several employees, including myself, have been dismissed without proper notice or severance pay, which is against the labor laws in Nigeria.",
    reportStatus: "submited",
    dateReportWasMade: "2/07/2024",
  },
  {
    report:
      "I am reporting an issue of unfair dismissal and lack of benefits at XYZ Manufacturing Company, located in the Ikeja Industrial Area of Lagos. Several employees, including myself, have been dismissed without proper notice or severance pay, which is against the labor laws in Nigeria.",
    reportStatus: "submited",
    dateReportWasMade: "2/07/2024",
  },
];

export const dashboardReportChartData = [
  {
    name: "Employment",
    uv: 40,
  },
];

export const limitDescription = (description: string, maxLength: number) => {
  if (description.length <= maxLength) {
    return description;
  }
  return description.slice(0, maxLength) + "...";
};

export const privacyPolicy = [
    {
        heading: "Information We Collect",
        subheading: ["Personal Information: We may collect personal information that you provide to us, such as your name, email address, phone number, and location when you create an account, submit a report, or contact us.",
            "Usage Data: We may collect information about your interactions with the Service, including the pages you visit, the features you use, the time and date of your visits, and other usage statistics.",
            "Device Information: We may collect information about the device you use to access the Service, including the device type, operating system, browser type, and IP address."],
    },
  {
    heading: "How We Use Your Information",
    subheading: [
      "To Provide and Maintain the Service: To create and manage your account, process your reports, and provide the features of the Service",
      "To Improve the Service: To understand how users interact with the Service and to enhance its functionality and user experience..",
      "To Communicate with You: To send you updates, notifications, and other information related to your use of the Service.",
      "To Ensure Security: To monitor and protect the security of the Service and its users.",
      "To Comply with Legal Obligations: To comply with applicable laws, regulations, and legal processes.",
    ],
  },
  {
    heading: "How We Share Your Information",
    subheading: [
      "With Service Providers: We may share your information with third-party service providers who perform services on our behalf, such as hosting, data analysis, and customer support.",
      "With Government Authorities: We may disclose your information to government authorities if required by law or to protect our legal rights.",
      "In Connection with Business Transactions: We may share your information in connection with a merger, acquisition, or sale of all or a portion of our assets.",
      "With Your Consent: We may share your information with third parties if you give us your consent to do so.",
    ],
  },
  {
    heading: "Data Security",
    headingDetails:
      "We implement appropriate technical and organizational measures to protect your personal information from unauthorized access, use, disclosure, and destruction. However, no security measure is perfect, and we cannot guarantee the absolute security of your information.",
  },
  {
    heading: "Data Retention",
    headingDetails:
      "We retain your personal information for as long as necessary to fulfill the purposes for which it was collected and to comply with legal obligations. When your information is no longer needed, we will securely delete or anonymize it.",
  },
];

export const termsOfService = [
  {
    heading: "User Account",
    headingDetails: [
      "Registration: You must create an account to use certain features of the Service. You agree to provide accurate and complete information during the registration process.",
      "Account Security: You are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account. Notify us immediately of any unauthorized use."
    ]
  },
  {
    heading: "User Conduct",
    headingDetails: [
      "Lawful Use: You agree to use the Service only for lawful purposes and in accordance with these Terms.",
      "Prohibited Activities: You agree not to engage in any of the following activities;Violating any applicable laws or regulations, Submitting false or misleading reports, Harassing, abusing, or harming other users and Interfering with or disrupting the Service."
    ]
  },
  {
    heading: "Submission of Reports",
    headingDetails: [
      "Accuracy: You agree to submit accurate and truthful reports. False or misleading information is strictly prohibited.",
      "Content Ownership: You retain ownership of the content you submit, but you grant us a worldwide, non-exclusive, royalty-free license to use, distribute, and display the content in connection with the Service.",
    ]
  },
  {
    heading: "Privacy Policy",
    headingDetails: [
      "Data Collection: We collect and use your personal information in accordance with our Privacy Policy.",
      "User Consent: By using the Service, you consent to our collection and use of your personal information as described in the Privacy Policy.",

    ]
  },
  {
    heading: "Intellectual Property",
    headingDetails: [
      'Ownership: All content and materials available on the Service, including but not limited to text, graphics, logos, and software, are the property of Speak Up 🇳🇬 or its licensors.',
      "Restrictions: You may not reproduce, distribute, modify, or create derivative works of any content from the Service without our prior written consent."
    ]
  },
  {
    heading: "Governing Law",
    details: "These Terms shall be governed by and construed in accordance with the laws of Nigeria, without regard to its conflict of law principles."
  },
  {
    heading: "Changes to Terms",
    details: "We reserve the right to modify these Terms at any time. We will notify you of any changes by posting the new Terms on the Service. Your continued use of the Service after such changes constitutes your acceptance of the new Terms."
  }
]
