import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import '../globals.css';
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const monsetserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${monsetserrat.className} bg-white-3`}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>

    </ClerkProvider>
  );
}
